spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=CTT&useUnicode=true&characterEncoding=utf8
    username: root
    password: test
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
      #最小连接数
      minimum-idle: 5
      connection-test-query: select 1 from dual
      #空闲连接超时时间
      idle-timeout: 500000