spring:
  datasource:
    driverClassName: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/test
    username: test
    password: test
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
      #最小连接数
      minimum-idle: 5
      connection-test-query: select 1 from dual
      #空闲连接超时时间
      idle-timeout: 500000